array_width = 40
attr_fn_like_width = 50
binop_separator = "Front"
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
chain_width = 50
combine_control_expr = false
comment_width = 60
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2018"
empty_single_line = true
enum_discrim_align_threshold = 30
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Vertical"
fn_call_width = 50
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = false
format_macro_bodies = false
format_strings = true
hard_tabs = false
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "Horizontal"
indent_style = "Block"
inline_attribute_width = 0
license_template_path = ""
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_arm_trailing_comma = true
max_width = 80
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
preserve_block_start_blank_lines = false
preserve_closure_block_wrapping = true
overflow_delimited_expr = false
removed_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
single_line_if_else_max_width = 0
space_after_colon = true
space_before_colon = false
space_before_fn_sig_paren = false
space_around_ranges = true
space_around_attr_eq = true
struct_field_align_threshold = 30
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = false
#width_heuristics = "Off"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
