name: Tag Version

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to tag'
        required: true
        default: 'main'

jobs:
  get-tag-version:
    runs-on: ubuntu-16.04
    outputs:
      version: ${{ steps.getcargoversion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: getcargoversion
        run: echo "::set-output name=version::"$(grep -i Version rs/Cargo.toml | cut -d= -f2 | tr -d '[ "]').$GITHUB_RUN_NUMBER

  tag-version:
    runs-on: ubuntu-16.04
    needs: [ get-tag-version ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - id: create-tag
        name: Create Tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ needs.get-tag-version.outputs.version }}",
              sha: context.sha
            })
